variable "name_prefix" {
  type = string
}

variable "subnet_ids" {
  description = "Private DB subnet ids."
  type        = list(string)
}

variable "security_group_id" {
  type = string
}

variable "instance_class" {
  type    = string
  default = "db.t4g.small"
}

variable "allocated_storage" {
  type    = number
  default = 20
}

variable "engine_version" {
  type    = string
  default = "16"
}

variable "db_name" {
  type    = string
  default = "aether"
}

variable "master_username" {
  type    = string
  default = "aether"
}

variable "master_password" {
  description = "Master password (generated by the stack, stored in Secrets Manager)."
  type        = string
  sensitive   = true
}

variable "high_availability" {
  description = "Gates Multi-AZ, deletion protection, backups, and final snapshot. false = fast, fully destroyable demo DB."
  type        = bool
  default     = false
}
